# Deep Learning Verkehrszeichen

Made by [Sharkbyteprojects](https://github.com/sharkbyteprojects)

Need
- Keras
- SKLEARN
- numpy

In [1]:
from keras.layers import Input
import numpy as np
from keras.layers import Dense
inputs=Input(shape=(4,))
fc=Dense(3)(inputs)
from keras.models import Model
model=Model(input=inputs,output=fc)

Using TensorFlow backend.
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: UserWarning: Update your `Model` call to the Keras 2 API: `Model(inputs=Tensor("in..., outputs=Tensor("de...)`
  import sys


Zeige infos über Model:

In [2]:
model.summary()

Model: "model_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         (None, 4)                 0         
_________________________________________________________________
dense_1 (Dense)              (None, 3)                 15        
Total params: 15
Trainable params: 15
Non-trainable params: 0
_________________________________________________________________


Compile and add new Neurons

In [3]:
model.compile(optimizer="adam",
             loss="categorical_crossentropy",
             metrics=["accuracy"])
predictionss=Dense(8,activation="softmax")(fc)
predictions=Dense(3,activation="softmax")(predictionss)

Test of Model:

In [4]:
az=model.predict(np.array([[5.1,5.3,1.4,0.2]]))

Recompile and Retry


In [5]:
model=Model(input=inputs,output=predictions)
model.compile(optimizer="adam",
             loss="categorical_crossentropy",
             metrics=["accuracy"])
model.summary()
aza=model.predict(np.array([[5.1,5.3,1.4,0.2]]))

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Model` call to the Keras 2 API: `Model(inputs=Tensor("in..., outputs=Tensor("de...)`
  """Entry point for launching an IPython kernel.


Model: "model_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         (None, 4)                 0         
_________________________________________________________________
dense_1 (Dense)              (None, 3)                 15        
_________________________________________________________________
dense_2 (Dense)              (None, 8)                 32        
_________________________________________________________________
dense_3 (Dense)              (None, 3)                 27        
Total params: 74
Trainable params: 74
Non-trainable params: 0
_________________________________________________________________


train it


In [6]:
from sklearn import datasets
iris =datasets.load_iris()
X=np.array(iris.data)
y=np.array(iris.target)
X.shape, y.shape
from keras.utils.np_utils import to_categorical
y=to_categorical(y,3)
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20,random_state=42,stratify=y)

complete prepare for train, start train:


In [7]:
model.fit(X_train, y_train,epochs=500,validation_split=0.3)

Train on 84 samples, validate on 36 samples
Epoch 1/500
84/84 [==============================] - 4s 48ms/step - loss: 1.1820 - accuracy: 0.3333 - val_loss: 1.1752 - val_accuracy: 0.3333
Epoch 2/500
84/84 [==============================] - 0s 429us/step - loss: 1.1767 - accuracy: 0.3333 - val_loss: 1.1705 - val_accuracy: 0.3333
Epoch 3/500
84/84 [==============================] - 0s 453us/step - loss: 1.1718 - accuracy: 0.3333 - val_loss: 1.1655 - val_accuracy: 0.3333
Epoch 4/500
84/84 [==============================] - 0s 357us/step - loss: 1.1664 - accuracy: 0.3333 - val_loss: 1.1604 - val_accuracy: 0.3333
Epoch 5/500
84/84 [==============================] - 0s 583us/step - loss: 1.1609 - accuracy: 0.3333 - val_loss: 1.1553 - val_accuracy: 0.3333
Epoch 6/500
84/84 [==============================] - 0s 345us/step - loss: 1.1553 - accuracy: 0.3333 - val_loss: 1.1503 - val_accuracy: 0.3333
Epoch 7/500
84/84 [==============================] - 0s 750us/step - loss: 1.1503 - accuracy: 0.333

C:\ProgramData\Anaconda3\lib\site-packages\keras\callbacks\callbacks.py:95: RuntimeWarning: Method (on_train_batch_end) is slow compared to the batch update (0.102024). Check your callbacks.
  % (hook_name, delta_t_median), RuntimeWarning)


Epoch 405/500
84/84 [==============================] - 0s 405us/step - loss: 0.5066 - accuracy: 0.8333 - val_loss: 0.5329 - val_accuracy: 0.8611
Epoch 406/500
84/84 [==============================] - 0s 369us/step - loss: 0.5063 - accuracy: 0.8333 - val_loss: 0.5327 - val_accuracy: 0.8611
Epoch 407/500
84/84 [==============================] - 0s 369us/step - loss: 0.5060 - accuracy: 0.8333 - val_loss: 0.5324 - val_accuracy: 0.8611
Epoch 408/500
84/84 [==============================] - 0s 333us/step - loss: 0.5058 - accuracy: 0.8333 - val_loss: 0.5321 - val_accuracy: 0.8611
Epoch 409/500
84/84 [==============================] - 0s 310us/step - loss: 0.5055 - accuracy: 0.8333 - val_loss: 0.5317 - val_accuracy: 0.8611
Epoch 410/500
84/84 [==============================] - 0s 488us/step - loss: 0.5053 - accuracy: 0.8333 - val_loss: 0.5314 - val_accuracy: 0.8611
Epoch 411/500
84/84 [==============================] - 0s 333us/step - loss: 0.5051 - accuracy: 0.8333 - val_loss: 0.5311 - val_ac

C:\ProgramData\Anaconda3\lib\site-packages\keras\callbacks\callbacks.py:95: RuntimeWarning: Method (on_train_batch_end) is slow compared to the batch update (0.135036). Check your callbacks.
  % (hook_name, delta_t_median), RuntimeWarning)


84/84 [==============================] - 0s 441us/step - loss: 0.4942 - accuracy: 0.8333 - val_loss: 0.5197 - val_accuracy: 0.8611
Epoch 453/500
84/84 [==============================] - 0s 393us/step - loss: 0.4939 - accuracy: 0.8333 - val_loss: 0.5194 - val_accuracy: 0.8611
Epoch 454/500
84/84 [==============================] - 0s 524us/step - loss: 0.4937 - accuracy: 0.8333 - val_loss: 0.5191 - val_accuracy: 0.8611
Epoch 455/500
84/84 [==============================] - 0s 357us/step - loss: 0.4934 - accuracy: 0.8333 - val_loss: 0.5188 - val_accuracy: 0.8611
Epoch 456/500
84/84 [==============================] - 0s 381us/step - loss: 0.4932 - accuracy: 0.8333 - val_loss: 0.5186 - val_accuracy: 0.8611
Epoch 457/500
84/84 [==============================] - 0s 286us/step - loss: 0.4929 - accuracy: 0.8333 - val_loss: 0.5183 - val_accuracy: 0.8611
Epoch 458/500
84/84 [==============================] - 0s 274us/step - loss: 0.4927 - accuracy: 0.8333 - val_loss: 0.5180 - val_accuracy: 0.8611

Test


In [8]:
print("1. 1 Neuron")
print(az)
print("2. 2 Neuron:")
print(aza)
print("3. Train")
print(model.predict(np.array([[5.1,5.3,1.4,0.2]])))

1. 1 Neuron
[[ 3.4176016 -1.428774  -2.350525 ]]
2. 2 Neuron:
[[0.22552678 0.33404663 0.44042662]]
3. Train
[[0.8928013  0.09092157 0.01627707]]


using testdata

In [9]:
train_loss, train_accuracy=model.evaluate(X_train, y_train)
train_loss, train_accuracy

120/120 [==============================] - 0s 167us/step


(0.4888818025588989, 0.8583333492279053)

In [10]:
train_loss, train_accuracy=model.evaluate(X_test, y_test)
train_loss, train_accuracy

30/30 [==============================] - 0s 367us/step


(0.48892590403556824, 0.8666666746139526)

### HOW TO:
Using This Iris Framework (Data in MM)

In [11]:
print(model.predict(np.array([[5.1,5.3,1.4,0.2]])))#RANGE: SEPAL LENGHT, SEPAL WIDTH,PETAL LENGHT, PETAL WIDTH

[[0.8928013  0.09092157 0.01627707]]


---

## Vergleich mit ML

In [12]:
Xy=iris.data
yy=iris.data
Xy_sepal_lenght=Xy[:,0]
Xy_sepal_width=Xy[:,1]
Xy_petal_lenght=Xy[:,2]
Xy_sepal_width=Xy[:,3]
from sklearn.model_selection import train_test_split
Xy_train, Xy_test, yy_train, yy_test=train_test_split(X,y,test_size=0.4)
#USING NEAREST NEIGHBORS
from sklearn import neighbors
clf=neighbors.KNeighborsClassifier(1)
clf.fit(Xy_train,yy_train)
print(clf.score(Xy_train,yy_train))
print(clf.score(Xy_test,yy_test))

1.0
0.9833333333333333


## Vergleich

In [13]:
print("Deep Learning:")
deplearn=model.predict(np.array([[6.3,2.7,5.5,1.5]]))
print("Probability for zero in percent")
print(round(deplearn[0][0]*100,1))
print("Probability for one in percent")
print(round(deplearn[0][1]*100,1))
print("Probability for two in percent")
print(round(deplearn[0][2]*100,1))

Deep Learning:
Probability for zero in percent
3.1
Probability for one in percent
40.9
Probability for two in percent
56.1


In [14]:
print("ML:")
clf.predict([[6.3,2.7,5.5,1.5]])

ML:


array([[0., 0., 1.]], dtype=float32)