# Deep Learning Verkehrszeichen

Made by [Sharkbyteprojects](https://github.com/sharkbyteprojects)

Need
- Keras
- SKLEARN
- numpy

In [84]:
from keras.layers import Input
import numpy as np
from keras.layers import Dense
inputs=Input(shape=(4,))
fc=Dense(3)(inputs)
from keras.models import Model
model=Model(input=inputs,output=fc)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: UserWarning: Update your `Model` call to the Keras 2 API: `Model(inputs=Tensor("in..., outputs=Tensor("de...)`
  import sys


Zeige infos über Model:

In [85]:
model.summary()

Model: "model_17"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_12 (InputLayer)        (None, 4)                 0         
_________________________________________________________________
dense_27 (Dense)             (None, 3)                 15        
Total params: 15
Trainable params: 15
Non-trainable params: 0
_________________________________________________________________


Compile:


In [86]:
model.compile(optimizer="adam",
             loss="categorical_crossentropy",
             metrics=["accuracy"])
predictionss=Dense(8,activation="softmax")(fc)
predictions=Dense(3,activation="softmax")(predictionss)

Test of Model:

In [87]:
az=model.predict(np.array([[5.1,5.3,1.4,0.2]]))

Recompile and Retry


In [88]:
model=Model(input=inputs,output=predictions)
model.compile(optimizer="adam",
             loss="categorical_crossentropy",
             metrics=["accuracy"])
model.summary()
aza=model.predict(np.array([[5.1,5.3,1.4,0.2]]))

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Model` call to the Keras 2 API: `Model(inputs=Tensor("in..., outputs=Tensor("de...)`
  """Entry point for launching an IPython kernel.


Model: "model_18"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_12 (InputLayer)        (None, 4)                 0         
_________________________________________________________________
dense_27 (Dense)             (None, 3)                 15        
_________________________________________________________________
dense_28 (Dense)             (None, 8)                 32        
_________________________________________________________________
dense_29 (Dense)             (None, 3)                 27        
Total params: 74
Trainable params: 74
Non-trainable params: 0
_________________________________________________________________


train it


In [89]:
from sklearn import datasets
iris =datasets.load_iris()
X=np.array(iris.data)
y=np.array(iris.target)
X.shape, y.shape
from keras.utils.np_utils import to_categorical
y=to_categorical(y,3)
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20,random_state=42,stratify=y)

complete prepare for train, start train:


In [90]:
model.fit(X_train, y_train,epochs=500,validation_split=0.3)

Train on 84 samples, validate on 36 samples
Epoch 1/500
84/84 [==============================] - 3s 30ms/step - loss: 1.1476 - accuracy: 0.3452 - val_loss: 1.1466 - val_accuracy: 0.3056
Epoch 2/500
84/84 [==============================] - 0s 488us/step - loss: 1.1444 - accuracy: 0.3452 - val_loss: 1.1425 - val_accuracy: 0.3056
Epoch 3/500
84/84 [==============================] - 0s 274us/step - loss: 1.1404 - accuracy: 0.3452 - val_loss: 1.1383 - val_accuracy: 0.3056
Epoch 4/500
84/84 [==============================] - 0s 321us/step - loss: 1.1365 - accuracy: 0.3214 - val_loss: 1.1342 - val_accuracy: 0.3056
Epoch 5/500
84/84 [==============================] - 0s 298us/step - loss: 1.1327 - accuracy: 0.2619 - val_loss: 1.1302 - val_accuracy: 0.2778
Epoch 6/500
84/84 [==============================] - 0s 369us/step - loss: 1.1288 - accuracy: 0.2262 - val_loss: 1.1262 - val_accuracy: 0.1944
Epoch 7/500
84/84 [==============================] - 0s 286us/step - loss: 1.1258 - accuracy: 0.190

Test


In [91]:
print("1. 1 Neuron")
print(az)
print("2. 2 Neuron:")
print(aza)
print("3. Train")
print(model.predict(np.array([[5.1,5.3,1.4,0.2]])))

1. 1 Neuron
[[0.3290987 2.4196131 1.7612818]]
2. 2 Neuron:
[[0.35916266 0.359181   0.2816563 ]]
3. Train
[[0.9206249  0.06314884 0.01622626]]


using testdata

In [92]:
train_loss, train_accuracy=model.evaluate(X_train, y_train)
train_loss, train_accuracy

120/120 [==============================] - 0s 150us/step


(0.4981271386146545, 0.8166666626930237)

In [93]:
train_loss, train_accuracy=model.evaluate(X_test, y_test)
train_loss, train_accuracy

30/30 [==============================] - 0s 100us/step


(0.4974057078361511, 0.8666666746139526)

### HOW TO:
Using This Iris Framework (Data in MM)

In [103]:
print(model.predict(np.array([[5.1,5.3,1.4,0.2]])))#RANGE: SEPAL LENGHT, SEPAL WIDTH,PETAL LENGHT, PETAL WIDTH

[[0.9206249  0.06314884 0.01622626]]


---

## Vergleich mit ML

In [107]:
Xy=iris.data
yy=iris.data
Xy_sepal_lenght=Xy[:,0]
Xy_sepal_width=Xy[:,1]
Xy_petal_lenght=Xy[:,2]
Xy_sepal_width=Xy[:,3]
from sklearn.model_selection import train_test_split
Xy_train, Xy_test, yy_train, yy_test=train_test_split(X,y,test_size=0.4)
#USING NEAREST NEIGHBORS
from sklearn import neighbors
clf=neighbors.KNeighborsClassifier(1)
clf.fit(Xy_train,yy_train)
print(clf.score(Xy_train,yy_train))
print(clf.score(Xy_test,yy_test))

1.0
0.9666666666666667


## Vergleich

In [118]:
print("Deep Learning:")
deplearn=model.predict(np.array([[6.3,2.7,5.5,1.5]]))
print("Probability for zero in percent")
print(round(deplearn[0][0]*100,1))
print("Probability for one in percent")
print(round(deplearn[0][1]*100,1))
print("Probability for two in percent")
print(round(deplearn[0][2]*100,1))

Deep Learning:
Probability for zero in percent
3.1
Probability for one in percent
43.5
Probability for two in percent
53.4


In [116]:
print("ML:")
clf.predict([[6.3,2.7,5.5,1.5]])

ML:


array([[0., 0., 1.]], dtype=float32)